[build]
  base = "frontend"
  
  publish = "build"
  
  # Comando compilador
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
